### ISSUE TITLE
Malformed byte-stream input to CharsetDecoder

### ISSUE THREAD

**Issue by shmish111** [ztellman/aleph#138] opened 2015-02-01 12:43 UTC
Not really sure this issue should go here as it's a combination of bytestreams and aleph and possibly just me doing something wrong.

The following gives `IllegalArgumentException Malformed byte-stream input to CharsetDecoder  byte-streams.char-sequence/parse-result (char_sequence.clj:17)`

```clojure
(-> @(http/get "http://www.google.ch/?gfe_rd=cr&ei=zhvOVNSyH6eH8QfbhoHoBg")
    :body
    bs/to-string)
```

Am I using `bs/to-string` incorrectly?  Looking at the response headers I can see the charset specified and I tried:

```clojure
(-> @(http/get "http://www.google.ch/?gfe_rd=cr&ei=zhvOVNSyH6eH8QfbhoHoBg")
    :body
    (bs/to-string {:charset "ISO-8859-1"}))
```

but the result is the same.

**Comment by ztellman** [comment] 2015-02-01 17:29
Just as a heads up, that endpoint seems to get a redirect, but if I follow the redirect I get the same error.  The fact that this doesn't get any such error:

```
(-> @(http/get "http://www.google.ch/?gfe_rd=cr&ei=zhvOVNSyH6eH8QfbhoHoBg")
    :body
    bs/to-byte-array
    bs/to-string)
```

Suggests the error is in https://github.com/ztellman/byte-streams/blob/master/src/byte_streams/char_sequence.clj, which is slightly surprising (that code's been around for a while), but I'll take a look and see what I can find.

**Comment by ztellman** [comment] 2015-02-01 18:21
Ha, okay, this took me way too long to figure out.  The problem is that you need to pass in `{:encoding "ISO-8859-1"}`, not `{:charset "ISO-8859-1"}`.  The secondary problem is that `(String. byte[])` is more forgiving of encoding issues than the alternate path.  Near term fix is to pass in the charset the proper way, longer term fix is for me to make the encoding errors less stringent, but configurable.

Marking this as closed.

**Closed by ztellman** 2015-02-01 18:21 UTC

**Comment by ztellman** [comment] 2015-02-01 18:31
The latest byte-streams `0.2.0-SNAPSHOT` will fix this so that the encoding doesn't need to be specified (though this may cause some characters to be replaced with placeholders).

**Comment by shmish111** [comment] 2015-02-01 18:49
Ah great.  One thing I don't understand then, if I use `(-> x bs/to-byte-array bs/to-string)` is this going to possibly replace some characters with placeholders as well?  Or is it using UTF8 and will be decoded incorrectly?

**Comment by ztellman** [comment] 2015-02-01 18:54
I'm not sure I understand the "or"; when it can't decode a particular
character it will replace it with a placeholder, which I'd consider
"incorrect" decoding.  However, it won't throw an error, and I've made it
so that both conversions with and without the `bs/to-byte-array` behave
consistently, by replacing unknown characters.  You can get the old
behavior by specifying `{:on-encoding-error :report}` in the options if you
like.

Does that make sense?

**Comment by shmish111** [comment] 2015-02-01 19:17
Yes, I think I understand now.  Thanks for the quick work and great communication again :)
