### ISSUE TITLE
HTTP Client Example with chain does not work

### ISSUE THREAD

**Issue by darren-fhf** [ztellman/aleph#151] opened 2015-02-15 20:36 UTC
Using aleph-0.4.0-beta2, Oracle Java 1.8.0_25

It could just be that I'm misunderstanding something here, but if I put the bs/to-string inside the chain, as it is in the README.md, it hangs forever.

````
(ns wr.play
  (:require [aleph.http        :as http]
            [manifold.deferred :as d]
            [byte-streams      :as bs]))

;;;; This works

(defn ex1 [url]
  (d/chain (http/get url) :body))

(-> @(ex1 "http://www.google.com") bs/to-string)

;;;; This hangs forever

(defn ex2 [url]
  (d/chain (http/get url) :body bs/to-string))

@(ex2 "http://www.google.com")
````

**Comment by ztellman** [comment] 2015-02-15 20:40
Are you using a specific version of Manifold, or just the transitive
dependency from Aleph?

**Comment by darren-fhf** [comment] 2015-02-15 20:43
Just the transitive dependency

**Comment by ztellman** [comment] 2015-02-16 00:51
Oh, I see the problem.  This is a duplicate of issue #137, which has been fixed but hasn't been put into a formal release.  I thought maybe I hadn't completely fixed this, but I expect if you target `0.4.0-SNAPSHOT` everything will work as expected.  I'm closing this issue, but will release `0.4.0-beta3` shortly.

**Closed by ztellman** 2015-02-16 00:51 UTC

**Comment by darren-fhf** [comment] 2015-02-16 19:19
Verified working with 0.4.0-SNAPSHOT. Looking forward to the -beta3 build.

**Comment by ztellman** [comment] 2015-02-17 04:24
beta3 is released
