### ISSUE TITLE
on-closed not fired when client closes connection

### ISSUE THREAD

**Issue by malcolmsparks** [ztellman/aleph#375] opened 2018-04-03 22:53 UTC
My context is that I'm trying to implement GraphQL subscriptions for Lacinia with aleph (with WS and SSE, but that's not relevant). A GraphQL subscription event might be for, say, my age changing. That happens once a year, so is rare. Ideally, if the client gets bored of waiting for that event they should be able to close the connection which should trigger the unsubscription of the event source.

Let's consider the following request handler:

```clojure
(defn handler [req]
  (let [s (ms/stream)]

    (ms/on-closed s (fn [] (println "Stream closed, so I can unsubscribe!")))

    {:status 200
     :headers {"content-type" "text/event-stream"}
     :body s}))
```

When I connect using `curl`, I see an empty event-stream, the connection remains alive (as it should) but when a `Ctrl-c` I don't get the expected "Stream closed, so I can unsubscribe!" message.

Let's amend the handler by adding some events:

```clojure
(defn handler [req]
  (let [s (ms/stream)]

    (ms/on-closed s (fn [] (println "Stream closed!")))

    (future
      (loop [n 1]
        (when (and (< n 100)
                   @(ms/put! s (str "data: " n "\r\n\r\n")))
          (Thread/sleep 100)
          (recur (inc n)))))

    {:status 200
     :headers {"content-type" "text/event-stream"}
     :body s}))
```

Now, if I connect with curl, I _do_ see the println message. To understand why, look at `aleph.http.server/ring-handler`.

```clojure
     :channel-inactive
      ([_ ctx]
        (when-let [s @stream]
          (s/close! s))
        (doseq [b @buffer]
          (netty/release b)))
```
When the client closes the channel we do indeed get the `:channel-inactive` event. However, the implementation then derefs the stream, which blocks until the next event (which in my contrived example might be a year away!). In the case I've got bored and closed the connection myself, the deref returns nil and so the `(s/close! s)` body isn't executed. 

So I don't get any notification to unsubscribe my subscriber. Of course, I can _wait_ (maybe a year) until the next event is generated and try to `put!` on the closed channel, and unsubscribing upon it returning false. I can also live with the assumption that GraphQL events _will_ be produced fairly frequently, but it doesn't feel at all efficient/optimal. 

Is there a better way of signalling the closing client connection rather than attempting to `put!` on the stream? It seems that given the fact that `:channel-inactive` is called by Netty to aleph, there should be a way of signalling 'user-space' code.

**Comment by kachayev** [comment] 2018-04-04 06:37
> However, the implementation then derefs the stream, which blocks until the next event (which in my contrived example might be a year away!).

`stream` here is an `atom` that holds `netty/channel` wrapped into `buffered-source` (when ready/necessary): https://github.com/ztellman/aleph/blob/5e22db5f99f259d0b3d3f70d6eddcd4a59cd6588/src/aleph/http/server.clj#L223 initialized with the value [here](https://github.com/ztellman/aleph/blob/5e22db5f99f259d0b3d3f70d6eddcd4a59cd6588/src/aleph/http/server.clj#L244) or [here](https://github.com/ztellman/aleph/blob/5e22db5f99f259d0b3d3f70d6eddcd4a59cd6588/src/aleph/http/server.clj#L304). Meaning that `deref` here is not blocking, it's just an access to the current state of the `atom`. So the code you've mentioned actually just checks: if we have a stream going, close it.

**Comment by malcolmsparks** [comment] 2018-04-04 06:43
Thanks for this info, it's very useful. My initial theory as to why I'm not seeing the on-closed callback called must be wrong. Why do you think the call back isn't called?

Here's a test case: https://github.com/juxt/aleph-issue

I'm seeing this with alpha5. I can try with older releases.

**Comment by kachayev** [comment] 2018-04-04 09:09
@malcolmsparks The code you're referring both in case of `ring-handler` and `raw-ring-handler` is the code responsible for reading the *request*. In the first case, it would convert request (even chunked) into `InputStream` (actually, something that looks like `InputStream`, but that's irrelevant for now), in the second case, it would just stream you `netty`'s `ByteBuf`s. But that's still the body of the request, not the response. 

If you're looking `on-closed` to be called on the stream that represents the body of your response, you need [`send-message`](https://github.com/ztellman/aleph/blob/63ef5279fead2570148a75413e12d69e7d8f81fb/src/aleph/http/core.clj#L375), that should call [`send-streaming-body`](https://github.com/ztellman/aleph/blob/63ef5279fead2570148a75413e12d69e7d8f81fb/src/aleph/http/core.clj#L242), which should close the source channel [here](https://github.com/ztellman/aleph/blob/63ef5279fead2570148a75413e12d69e7d8f81fb/src/aleph/http/core.clj#L293-L297) as `close` is properly propagated through upstream<->downstream connection [here](https://github.com/ztellman/aleph/blob/63ef5279fead2570148a75413e12d69e7d8f81fb/src/aleph/http/core.clj#L281) 🤔 

Hope that reveals some useful insights. But I cannot reproduce the issue. Using `curl` and your code:

```clojure
(require '[aleph.http :as http])
=> nil
(require '[manifold.stream :as s])
=> nil
(defn handler [req]
  (let [s' (s/stream)]

    (s/on-closed s' (fn [] (println "Stream closed!")))
    (s/on-drained s' (fn [] (println "Stream is drained!")))

    (future
      (loop [n 1]
        (when (and (< n 100)
                   @(s/put! s' (str "data: " n "\r\n\r\n")))
          (Thread/sleep 100)
          (recur (inc n)))))

    {:status 200
     :headers {"content-type" "text/event-stream"}
     :body s'}))

=> #'user/handler
(def server (http/start-server handler {:port 8080}))
=> #'user/server
Stream closed!
Stream is drained!
```

**Comment by ztellman** [comment] 2018-04-04 17:17
I think changing `src` to `body` in the linked line would be fine, and probably preferable.  Manifold doesn't handle upstream propagation of closed streams right now, so performing the `close!` as far upstream as possible is ideal.

There is an open issue on Manifold to allow for upstream propagation, which I started poking at a while back, but didn't finish.  Linking it here for cross-referencing: https://github.com/ztellman/manifold/issues/128.

**Comment by kachayev** [comment] 2018-06-19 21:04
@ztellman I think it's safe now to close this issue 🤔

**Closed** 2018-06-19 22:40 UTC
