### ISSUE TITLE
set manifold to latest 0.1.5-alphaN -> 0.1.5

### ISSUE THREAD

**Issue by tuddman** [ztellman/aleph#266] opened 2016-08-04 16:08 UTC
attempting to use `aleph-0.4.2-alpha6`

complains:
```
CompilerException java.lang.RuntimeException: No such var: executor/with-executor, compiling:(aleph/http.clj:203:5) 
```

culprit [here](https://github.com/ztellman/aleph/blob/master/project.clj#L8)

setting the `manifold` dependency to `0.1.5` and installing locally solved it.

**Comment by xsc** [comment] 2016-08-04 19:16
Might be a duplicate of #261.

**Comment by ztellman** [comment] 2016-08-04 20:08
I think the `with-executor` macro is available in Manifold `0.1.5-alpha2`, were you explicitly specifying the version before?

**Comment by tuddman** [comment] 2016-08-04 21:14
Right, looks like it was/is there..

I'm using `aleph-0.4.2-alpha6` as a dependency.  That version was set explicitly in my `project.clj`

when loading the project in a REPL, got the error mentioned above.

so I cloned aleph,  and set its manifold dependency explicitly from `0.1.5-alpha2` to `0.1.5` and `lein install`'ed locally ... and error went away

**Comment by ztellman** [comment] 2016-08-04 21:33
Why are you cloning aleph and not just adding `[manifold "0.1.5"]` to your own project.clj?

**Comment by tuddman** [comment] 2016-08-04 21:48
sure, could've done that, I guess. I like to keep deps list to only that which I'm actually using directly.

call it scars from java and having to deal with sub-dependency version clashes.

**Comment by lvh** [comment] 2016-08-28 15:31
Looks like this issue should probably be closed?

**Comment by tuddman** [comment] 2016-08-28 16:00
https://github.com/ztellman/aleph/blob/master/project.clj#L8

is still at `1.5.0-alpha2`

**Comment by ztellman** [comment] 2016-08-28 16:03
Sorry, had some local changes I hadn't pushed yet.  It should be 1.5.0 now.

**Closed by ztellman** 2016-08-28 16:03 UTC

**Comment by lvh** [comment] 2016-08-28 16:05
No need to apologize 😄 Just trying to do my part by weeding through the issue tracker...
